// var resposta = document.getElementById('resposta')

// var frutas = ["Abacate", "Maçâ", "Uva", "Goiaba"];

// var frutaUsuario = prompt("Digite o nome de uma fruta");


// resposta.innerHTML = buscar(frutas, frutaUsuario);


// function buscar(frutas, user){
//     if(frutas.indexOf(user)>=0){
//         return "Fruta encontrada no índice: " +frutas.indexOf(user);
//         } else {
//             return "Fruta não encontrada"
//         }
//         }

// var array = [];

// array.push(Number(prompt("Digite o número"))) 
// array.push(Number(prompt("Digite o segundo número"))) 
// array.push(Number(prompt("Digite o terceiro número")))

// document.write(array)

// array.pop();

// document.write("O novo array é: " + array)

// const cores = ["Amarelo", "Vermelho", "Azul", "Violeta"];
// document.write("As cores são: " +cores + "<br>");

// cores.unshift("Preto");
// document.write("Adição de cor: "+cores+ "<br>");

// cores.shift();
// document.write("Cores finais: " + cores+ "<br>")

// var array = [10,20,30,40,50,60];

// document.write(array + "<br>")

// let novoArray = array.slice(2, 4);

// document.write(novoArray  + "<br>")

// var array = ["Pedro", "Augusto", "Marcos", "Matheus", "João"]

// array.splice(0,1,"Diego");

// document.write(array + "<br>")

// array.splice(0,2,"Diego");

// document.write(array + "<br>")

// array.splice(0,3,"Diego");

// document.write(array + "<br>")

// array.splice(0,4,"Diego");

// document.write(array + "<br>")
